# Basic
name:               "Wagner Research Group"
title:              "David Wagner's Research Group at UC Berkeley"
description:        "David Wagner's Research Group at UC Berkeley"


# URL
url:                https://wagner-group.github.io
baseurl:            
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Highlighter
highlighter:        rouge

# Navigation
nav:
  - name:           "projects"
    href:           "/projects"
  # - name:           "blog"
  #   href:           "/blog"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "projects"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "people"
    values:
      layout:       "profile"


collections:
  people:
    output: true
    permalink: /people/:title/index.html
  projects:
    output: true
    permalink: /projects/:title/index.html